"""decision counter_offer_discount_pct

Revision ID: 01c4917ca111
Revises: 38d7194a76b6
Create Date: 2026-09-03 11:41:19.301062

Adds `decision.counter_offer_discount_pct` (nullable Numeric(5,2)) so a
persisted Decision is a faithful copy of the PolicyDecision the engine
returned — it already stored `counter_offer_price`; this pins the discount
percentage at decision time too.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '01c4917ca111'
down_revision: Union[str, None] = '38d7194a76b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decision', sa.Column('counter_offer_discount_pct', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decision', 'counter_offer_discount_pct')
    # ### end Alembic commands ###
