"""initial schema

Revision ID: 44a6dc22308b
Revises: 
Create Date: 2026-09-03 10:26:32.965279
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '44a6dc22308b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('AI_BUYER', 'EXTERNAL', name='agenttype', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DISABLED', name='agentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('max_transaction_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allowed_actions', sa.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_transaction_amount >= 0', name='ck_agent_max_txn_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('ref_type', sa.String(length=40), nullable=False),
    sa.Column('ref_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash'),
    sa.UniqueConstraint('seq')
    )
    op.create_index(op.f('ix_audit_event_ref_id'), 'audit_event', ['ref_id'], unique=False)
    op.create_index(op.f('ix_audit_event_ref_type'), 'audit_event', ['ref_type'], unique=False)
    op.create_table('merchant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('policy_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('max_discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('min_margin_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_discount_pct >= 0 AND max_discount_pct <= 100', name='ck_product_max_discount_pct_range'),
    sa.CheckConstraint('min_margin_price >= 0 AND min_margin_price <= price', name='ck_product_margin_not_above_price'),
    sa.CheckConstraint('price >= 0', name='ck_product_price_nonneg'),
    sa.CheckConstraint('stock >= 0', name='ck_product_stock_nonneg'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_category'), 'product', ['category'], unique=False)
    op.create_index(op.f('ix_product_merchant_id'), 'product', ['merchant_id'], unique=False)
    op.create_table('action_request',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.Enum('PURCHASE', 'ACCEPT_COUNTER_OFFER', name='actiontype', native_enum=False, length=32), nullable=False),
    sa.Column('requested_discount_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('requested_quantity', sa.Integer(), nullable=True),
    sa.Column('proposed_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('raw_input', sa.Text(), nullable=True),
    sa.Column('parsed_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'PARSED', 'VALIDATED', 'INVALID', 'DECIDED', 'EXECUTED', 'FAILED', name='actionrequeststatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name='ck_action_request_confidence_range'),
    sa.CheckConstraint('requested_discount_pct IS NULL OR (requested_discount_pct >= 0 AND requested_discount_pct <= 100)', name='ck_action_request_discount_range'),
    sa.CheckConstraint('requested_quantity IS NULL OR requested_quantity > 0', name='ck_action_request_qty_positive'),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_request_agent_id'), 'action_request', ['agent_id'], unique=False)
    op.create_index(op.f('ix_action_request_product_id'), 'action_request', ['product_id'], unique=False)
    op.create_table('decision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action_request_id', sa.UUID(), nullable=False),
    sa.Column('verdict', sa.Enum('ALLOW', 'DENY', 'NEEDS_APPROVAL', 'COUNTER_OFFER', name='verdict', native_enum=False, length=32), nullable=False),
    sa.Column('policy_rule_id', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('counter_offer_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('policy_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_request_id'], ['action_request.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_request_id', name='uq_decision_action_request'),
    sa.UniqueConstraint('id', 'verdict', name='uq_decision_id_verdict')
    )
    op.create_index(op.f('ix_decision_action_request_id'), 'decision', ['action_request_id'], unique=False)
    op.create_table('approval',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('approver', sa.String(length=120), nullable=False),
    sa.Column('outcome', sa.Enum('APPROVED', 'REJECTED', name='approvaloutcome', native_enum=False, length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decision.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id', name='uq_approval_decision')
    )
    op.create_index(op.f('ix_approval_decision_id'), 'approval', ['decision_id'], unique=False)
    op.create_table('payment_attempt',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('decision_verdict', sa.Enum('ALLOW', 'DENY', 'NEEDS_APPROVAL', 'COUNTER_OFFER', name='verdict', native_enum=False, length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_payment_link_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'PAID', 'FAILED', 'EXPIRED', name='paymentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision_verdict = 'ALLOW'", name='ck_payment_attempt_verdict_is_allow'),
    sa.ForeignKeyConstraint(['decision_id', 'decision_verdict'], ['decision.id', 'decision.verdict'], name='fk_payment_attempt_allow_decision'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id', name='uq_payment_attempt_decision'),
    sa.UniqueConstraint('idempotency_key', name='uq_payment_attempt_idempotency_key')
    )
    op.create_index(op.f('ix_payment_attempt_decision_id'), 'payment_attempt', ['decision_id'], unique=False)
    op.create_table('webhook_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(length=80), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('payment_attempt_id', sa.UUID(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_attempt_id'], ['payment_attempt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_event_event_id'), 'webhook_event', ['event_id'], unique=True)
    op.create_index(op.f('ix_webhook_event_payment_attempt_id'), 'webhook_event', ['payment_attempt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_event_payment_attempt_id'), table_name='webhook_event')
    op.drop_index(op.f('ix_webhook_event_event_id'), table_name='webhook_event')
    op.drop_table('webhook_event')
    op.drop_index(op.f('ix_payment_attempt_decision_id'), table_name='payment_attempt')
    op.drop_table('payment_attempt')
    op.drop_index(op.f('ix_approval_decision_id'), table_name='approval')
    op.drop_table('approval')
    op.drop_index(op.f('ix_decision_action_request_id'), table_name='decision')
    op.drop_table('decision')
    op.drop_index(op.f('ix_action_request_product_id'), table_name='action_request')
    op.drop_index(op.f('ix_action_request_agent_id'), table_name='action_request')
    op.drop_table('action_request')
    op.drop_index(op.f('ix_product_merchant_id'), table_name='product')
    op.drop_index(op.f('ix_product_category'), table_name='product')
    op.drop_table('product')
    op.drop_table('merchant')
    op.drop_index(op.f('ix_audit_event_ref_type'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_ref_id'), table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_table('agent')
    # ### end Alembic commands ###
